version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    env_file:
      - ./src/.env
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    env_file:
      - ./src/.env
